### ISSUE TITLE
Remove Google Analytics

### ISSUE THREAD

**Issue by DavidLibeau** [rozierguillaume/trackwatt-web#4]
As for https://github.com/CovidTrackerFr/vitemadose-android/issues/43, I'm asking once again to remove Google tools in order to respect users' privacy.

It is illegal for 3 reasons:
1. Use without proper information (nothing on https://trackmywatt.fr/mentions_legales.html).
2. No consent asked (read https://lincnil.github.io/Guide-RGPD-du-developpeur/#Fiche_n%C2%B017%C2%A0:_Mesurer_la_fr%C3%A9quentation_de_vos_sites_web_et_de_vos_applications).
3. Transfert of personal data to the USA (read https://www.cnil.fr/fr/cookies-et-autres-traceurs/regles/questions-reponses-sur-les-mises-en-demeure-de-la-cnil-concernant-lutilisation-de-google-analytics).

**Comment by arthurmadecprevost** [comment]
What about [Matomo](https://fr.matomo.org/) instead ?

**Comment by DavidLibeau** [comment]
Yes, if you follow this guide: https://fr.matomo.org/faq/how-to/how-do-i-configure-matomo-without-tracking-consent-for-french-visitors-cnil-exemption/

**Comment by rozierguillaume** [comment]
Resolved in https://github.com/rozierguillaume/trackwatt-web/commit/b69f5c526b3e0cae71522df64d79ac552ebcad1e

**Comment by DavidLibeau** [comment]
Thanks! Will you also consider removing similar tracking systems from CovidTracker's projets? I opened several issues (https://github.com/CovidTrackerFr/vitemadose-android/issues/43, https://github.com/CovidTrackerFr/vitemadose-ios/issues/60#issuecomment-826357700) and PR: https://github.com/CovidTrackerFr/vitemadose-android/pull/86. For CovidTracker, the lines to remove are here: https://github.com/CovidTrackerFr/covidtracker-web/blob/main/_config.yml#L53.
